<?php
require_once __DIR__ . '/../Lib/functions.php';
?>

<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel='stylesheet' type='text/css' href='stylesheet.css'/>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
</head>
<body>
<?php if(isLoggedIn()): ?>
    You are already signed! Back to <a href="index.php">home</a>?
<?php else : ?>
    <div id="wrapper">
        <form method="post" name="registrationForm" action="login.php?go=/index.php">
            <label for="loginLoginInput">Login:</label> <input type="text" name="login" value="<?= htmlspecialchars($login, ENT_QUOTES)?>" id="loginLoginInput">
            <?php if($errors['login'] != "") : ?>
                <span style='color:red;'><?= $errors['login'] ?></span>
            <?php endif; ?>
            <br>

            <label for="passwordLoginInput">Password:</label> <input type="password" name="password" value="" id="passwordLoginInput">
            <?php if ($errors['password'] != "") : ?>
                <span style='color:red;'><?= $errors['password'] ?></span>
            <?php endif; ?>
            <br>
            <input type="checkbox" name="rememberMe" id="loginRememberMe"> <label for="loginRememberMe">Remember me.</label><br>
            <input type="submit" name="signIn" value="Submit!">
        </form>
    </div>
<?php endif; ?>
</body>
</html>