<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel='stylesheet' type='text/css' href='stylesheet.css'/>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
</head>
<body>
<div id="wrapper">
    <form method="post" name="registrationForm" action="login.php?go=index.php">
        Login: <input type="text" name="login" value="<?= htmlspecialchars($login, ENT_QUOTES)?>">
        <?php if($errors['login'] != "") : ?>
            <span style='color:red;'><?= $errors['login'] ?></span>
        <?php endif; ?>
        <br>

        Password: <input type="password" name="password" value="">
        <?php if ($errors['password'] != "") : ?>
            <span style='color:red;'><?= $errors['password'] ?></span>
        <?php endif; ?>
        <br>

        <input type="submit" name="signIn" value="Submit!">
    </form>
</div>
</body>
</html>