<?php
require_once __DIR__ . '/../Lib/functions.php';
?>

<!DOCTYPE html>
<html>
<head>
    <title>Registration</title>
    <link rel='stylesheet' type='text/css' href='stylesheet.css'/>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
</head>
<body>
<?php if(isLoggedIn()): ?>
    You are signed!  Back to <a href="index.php">home</a>?
<?php else : ?>
<div id="wrapper">
    <form method="post" name="registrationForm" action="registration.php?go=/index.php">
        <label for="passwordLoginInput">Login:</label> <input type="text" name="login" value="<?= htmlspecialchars($login, ENT_QUOTES)?>" id="passwordLoginInput">
        <?php if($errors['login'] != "") : ?>
            <span style='color:red;'><?= $errors['login'] ?></span>
        <?php endif; ?>
        <br>

        <label for="passwordPasswordInput">Password:</label> <input type="password" name="password" value="" id="passwordPasswordInput">
        <?php if ($errors['password'] != "") : ?>
            <span style='color:red;'><?= $errors['password'] ?></span>
        <?php endif; ?>
        <br>

        <label for="retryPasswordInput">Retry Password:</label> <input type="password" name="retryPassword" value="" id="retryPasswordInput">
        <?php if ($errors['retryPassword'] != "") : ?>
            <span style='color:red;'><?= $errors['retryPassword'] ?></span>
        <?php endif; ?>
        <br>

        <input type="submit" name="signUp" value="Register me!">
    </form>
</div>
<?php endif; ?>
</body>
</html>